package com.kloudtek.mule.elogging.log4j2;

import org.apache.logging.log4j.message.Message;

import java.util.Map;

/**
 * A json message allows to include extra attributes that will incorporated into a json string generated by {@link ELJsonLayout}
 */
public class JsonLogMessage implements Message {
    private Map<String, String> attributes;
    public JsonLogMessage(Map<String, String> attributes) {
        this.attributes = attributes;
    }

    public Map<String, String> getAttributes() {
        return attributes;
    }

    @Override
    public String getFormattedMessage() {
        return null;
    }

    @Override
    public String getFormat() {
        return null;
    }

    @Override
    public Object[] getParameters() {
        return new Object[0];
    }

    @Override
    public Throwable getThrowable() {
        return null;
    }
}
