#%RAML 1.0

baseUri: http://localhost:8081/
title: ELogging example
version: v1
mediaType: application/json

/test:
  get:
    description: Return a standard response.
    responses:
      200:
        body:
/testfail:
  get:
    description: Calls an API that will fail
    responses:
      500:
        body:
